#!/usr/bin/env python3
"""Regenerate uf2_xz_tables.h: slicing-by-16 tables for the .xz CRC32 and CRC64.

    python3 tools/gen_xz_tables.py > uf2_xz_tables.h

Table 0 is the classic byte-at-a-time table of the reflected polynomial; table k
advances table k-1 by one more zero byte. Checked against the standard check
values of the string "123456789" before anything is written.
"""
import sys

N = 16
POLY32 = 0xEDB88320            # IEEE 802.3, reflected
POLY64 = 0xC96C5795D7870F42    # ECMA-182, reflected


def tables(poly):
    t0 = []
    for i in range(256):
        c = i
        for _ in range(8):
            c = (c >> 1) ^ (poly if c & 1 else 0)
        t0.append(c)
    t = [t0]
    for k in range(1, N):
        t.append([(t[k - 1][i] >> 8) ^ t0[t[k - 1][i] & 0xFF] for i in range(256)])
    return t


def check(t0, bits, data):
    mask = (1 << bits) - 1
    c = mask
    for b in data:
        c = t0[(c ^ b) & 0xFF] ^ (c >> 8)
    return c ^ mask


c32, c64 = tables(POLY32), tables(POLY64)
assert check(c32[0], 32, b"123456789") == 0xCBF43926
assert check(c64[0], 64, b"123456789") == 0x995DC9BBDF1939FA


# ---- constants for folding with a carry-less multiply (PCLMULQDQ, PMULL) ----
#
# A 128-bit fold state X is read in the reflected order of the data: bit k of the
# little-endian 128-bit value is the coefficient of x^(127-k), so the low 64-bit
# lane holds the high-degree half H and the high lane the low half L, and
# X = H*x^64 + L. A carry-less multiply of two such 64-bit values a (A) and b (B)
# gives, read the same way over 128 bits, A*B*x. Advancing X by n bits,
# X*x^n = H*x^(n+64) + L*x^n, is therefore clmul(H, K(n+63)) ^ clmul(L, K(n-1)),
# where K(e) is x^e mod P written as a reflected 64-bit value (the coefficient of
# x^i in bit 63-i). The result is congruent to X*x^n modulo P and fits in 128 bits.
# Folded down to one state congruent to the data, the state itself is a 16-byte
# message with the same CRC, which the table code finishes.

def xpow_mod(e, poly_normal, w):
    """x^e mod P, P = x^w + poly_normal, as an integer with bit i = x^i."""
    r = 1
    top = 1 << w
    for _ in range(e):
        r <<= 1
        if r & top:
            r ^= top | poly_normal
    return r


def refl64(v):
    return int("{:064b}".format(v)[::-1], 2)


def fold_constants(poly_normal, w):
    return {n: refl64(xpow_mod(n, poly_normal, w)) for n in (127, 191, 511, 575)}


K32 = fold_constants(0x04C11DB7, 32)
K64 = fold_constants(0x42F0E1EBA9EA3693, 64)


def clmul(a, b):
    r = 0
    while b:
        if b & 1:
            r ^= a
        a <<= 1
        b >>= 1
    return r


def fold_reference(t0, bits, k, data, crc):
    """The C algorithm, on integers: fold four lanes of 16 bytes, merge them, fold
    single blocks, then let the table finish the state and the tail."""
    mask = (1 << bits) - 1
    reg = crc ^ mask
    lo = lambda x: x & ((1 << 64) - 1)
    hi = lambda x: x >> 64
    fold = lambda x, a, b: clmul(lo(x), k[a]) ^ clmul(hi(x), k[b])
    block = lambda i: int.from_bytes(data[i:i + 16], "little")
    x = [block(16 * j) for j in range(4)]
    x[0] ^= reg
    p = 64
    while len(data) - p >= 64:
        x = [fold(x[j], 575, 511) ^ block(p + 16 * j) for j in range(4)]
        p += 64
    s = x[0]
    for j in range(1, 4):
        s = fold(s, 191, 127) ^ x[j]
    while len(data) - p >= 16:
        s = fold(s, 191, 127) ^ block(p)
        p += 16
    r = 0
    for b in s.to_bytes(16, "little") + data[p:]:
        r = t0[(r ^ b) & 0xFF] ^ (r >> 8)
    return r ^ mask


def table_crc(t0, bits, data, crc):
    mask = (1 << bits) - 1
    c = crc ^ mask
    for b in data:
        c = t0[(c ^ b) & 0xFF] ^ (c >> 8)
    return c ^ mask


import random
rnd = random.Random(1)
for n in (64, 65, 79, 80, 127, 128, 200, 1000):
    d = bytes(rnd.randrange(256) for _ in range(n))
    for init in (0, 0x12345678, (1 << 64) - 1):
        assert fold_reference(c32[0], 32, K32, d, init & 0xFFFFFFFF) == table_crc(c32[0], 32, d, init & 0xFFFFFFFF), ("crc32", n)
        assert fold_reference(c64[0], 64, K64, d, init) == table_crc(c64[0], 64, d, init), ("crc64", n)

out = ["/* Generated by tools/gen_xz_tables.py - do not edit.",
       " * Slicing-by-%d tables for the reflected polynomials CRC32 0xEDB88320" % N,
       " * (IEEE 802.3) and CRC64 0xC96C5795D7870F42 (ECMA-182): table 0 is the classic",
       " * byte-at-a-time table, and table k advances table k-1 by one more zero byte.",
       " * Constant, so they need no runtime initialization and are safe from any thread. */",
       "", "#define XZ_CRC_SLICES %d" % N, "", "static const U32 crc32Table[%d][256] = {" % N]
for k in range(N):
    out.append("  {")
    for i in range(0, 256, 6):
        out.append("    " + ", ".join("0x%08X" % v for v in c32[k][i:i + 6]) + ",")
    out.append("  },")
out += ["};", "", "static const U64 crc64Table[%d][256] = {" % N]
for k in range(N):
    out.append("  {")
    for i in range(0, 256, 3):
        out.append("    " + ", ".join("0x%016XULL" % v for v in c64[k][i:i + 3]) + ",")
    out.append("  },")
out += ["};", "",
        "/* Fold constants for a carry-less multiply: XZ_CRCnn_K[e] is x^e mod P as a",
        " * reflected 64-bit value, for e = 127, 191, 511, 575 in that order. Checked",
        " * against the tables above by simulating the fold before this file was written. */",
        "static const U64 XZ_CRC32_K[4] = { " + ", ".join("0x%016XULL" % K32[n] for n in (127, 191, 511, 575)) + " };",
        "static const U64 XZ_CRC64_K[4] = { " + ", ".join("0x%016XULL" % K64[n] for n in (127, 191, 511, 575)) + " };",
        ""]
sys.stdout.write("\n".join(out))
