#!/usr/bin/env python3
"""Regenerate uf2_xz_tables.h: slicing-by-16 tables for the .xz CRC32 and CRC64.

    python3 tools/gen_xz_tables.py > uf2_xz_tables.h

Table 0 is the classic byte-at-a-time table of the reflected polynomial; table k
advances table k-1 by one more zero byte. Checked against the standard check
values of the string "123456789" before anything is written.
"""
import sys

N = 16
POLY32 = 0xEDB88320            # IEEE 802.3, reflected
POLY64 = 0xC96C5795D7870F42    # ECMA-182, reflected


def tables(poly):
    t0 = []
    for i in range(256):
        c = i
        for _ in range(8):
            c = (c >> 1) ^ (poly if c & 1 else 0)
        t0.append(c)
    t = [t0]
    for k in range(1, N):
        t.append([(t[k - 1][i] >> 8) ^ t0[t[k - 1][i] & 0xFF] for i in range(256)])
    return t


def check(t0, bits, data):
    mask = (1 << bits) - 1
    c = mask
    for b in data:
        c = t0[(c ^ b) & 0xFF] ^ (c >> 8)
    return c ^ mask


c32, c64 = tables(POLY32), tables(POLY64)
assert check(c32[0], 32, b"123456789") == 0xCBF43926
assert check(c64[0], 64, b"123456789") == 0x995DC9BBDF1939FA

out = ["/* Generated by tools/gen_xz_tables.py - do not edit.",
       " * Slicing-by-%d tables for the reflected polynomials CRC32 0xEDB88320" % N,
       " * (IEEE 802.3) and CRC64 0xC96C5795D7870F42 (ECMA-182): table 0 is the classic",
       " * byte-at-a-time table, and table k advances table k-1 by one more zero byte.",
       " * Constant, so they need no runtime initialization and are safe from any thread. */",
       "", "#define XZ_CRC_SLICES %d" % N, "", "static const U32 crc32Table[%d][256] = {" % N]
for k in range(N):
    out.append("  {")
    for i in range(0, 256, 6):
        out.append("    " + ", ".join("0x%08X" % v for v in c32[k][i:i + 6]) + ",")
    out.append("  },")
out += ["};", "", "static const U64 crc64Table[%d][256] = {" % N]
for k in range(N):
    out.append("  {")
    for i in range(0, 256, 3):
        out.append("    " + ", ".join("0x%016XULL" % v for v in c64[k][i:i + 3]) + ",")
    out.append("  },")
out += ["};", ""]
sys.stdout.write("\n".join(out))
